#!/bin/sh
# drift-report.md.sh — render a DriftReport JSON (from
# verifier-core.ts) as a markdown report on stdout.
#
# Usage: cat drift.json | drift-report.md.sh > session-drift.md
# Or:    tsx verifier-core.ts | drift-report.md.sh > session-drift.md
#
# This is the deterministic (no-LLM) report renderer. The
# output schema matches the LLM-formatted report in the
# verifier subagent's system prompt.
#
# Implementation: pure POSIX sh + awk + printf + grep. No jq
# (so the renderer is portable to any POSIX system; users
# without jq can still run the no-LLM path). The DriftReport
# JSON is read into a shell variable; awk walks the items
# and prints the markdown.

set -e

# Read the entire JSON from stdin into a variable.
REPORT_JSON=$(cat)

# Extract scalar fields. The DriftReport JSON is generated by
# us (verifier-core.ts), so the structure is known. Use awk
# with carefully constructed patterns that match the literal
# field name + ":" + value. For string values, the value
# ends at the next unescaped quote; for numeric values, the
# value is a contiguous run of digits.
#
# Pattern: "fieldname":<whitespace><value>
# We use awk's match() function with a capture group.

# Helper: extract a string field's value (between the
# field's quotes and the closing quote). Uses sed for
# portability (avoiding awk's match-with-array which is a
# gawk extension).
#
# Usage: extract_str <fieldname>
# Reads REPORT_JSON from the enclosing scope.
extract_str() {
  _field="$1"
  # Match "field":"value"; value is up to the next unescaped
  # quote. For our generated JSON, the values contain no
  # escaped quotes (no nested quotes, no backslashes in
  # subject lines), so a simple pattern suffices.
  printf '%s' "$REPORT_JSON" \
    | sed -n "s/.*\"$_field\":\"\\([^\"]*\\)\".*/\\1/p" \
    | head -n 1
}

# Helper: extract a numeric field's value. Matches
# "field":<number>.
extract_num() {
  _field="$1"
  printf '%s' "$REPORT_JSON" \
    | sed -n "s/.*\"$_field\":\\([0-9][0-9]*\\).*/\\1/p" \
    | head -n 1
}

TIMESTAMP=$(extract_str timestamp)
TOTAL=$(extract_num total)
FROM=$(extract_str from)
TO=$(extract_str to)

# Header section
printf '# Session drift report\n\n'
printf '## Header\n\n'
printf -- '- **Timestamp:** %s\n' "${TIMESTAMP:-unknown}"
printf -- '- **Range:** %s..%s\n' "${FROM:-root}" "${TO:-HEAD}"
printf -- '- **Total commits analyzed:** %s\n\n' "${TOTAL:-0}"

# Count items by category. Grep -c counts matching lines;
# for our generated JSON, each item is on its own line(s)
# and the category is unambiguous.
count_category() {
  _cat="$1"
  printf '%s' "$REPORT_JSON" | grep -c "\"category\":\"$_cat\"" || true
}

ITEM_COUNT=$(printf '%s' "$REPORT_JSON" | grep -c '"category":' || true)
MISSING_ARCHIVE=$(count_category missing-archive)
MISSING_HASH=$(count_category missing-hash)
MULTIPLE_TRAILERS=$(count_category multiple-trailers)
NO_TRAILER=$(count_category no-trailer)
WARN_COUNT=$(extract_num warnings_count)

# Warnings count: the warnings array is a JSON array of
# strings. Count by counting the number of quoted strings
# between "warnings":[ and "items":. We can approximate by
# counting the length of the warnings array, but the cleanest
# way is to extract the array contents and count newlines.
# The format is ["warn1","warn2",...].
WARN_COUNT=$(printf '%s' "$REPORT_JSON" \
  | sed -n 's/.*"warnings":\[\(.*\)\],"items".*/\1/p' \
  | tr ',' '\n' | grep -c '"' || true)
[ -z "$WARN_COUNT" ] && WARN_COUNT=0

# Severity
if [ "$ITEM_COUNT" = "0" ] && [ "$WARN_COUNT" = "0" ]; then
  SEVERITY="CLEAN"
elif [ "$MISSING_ARCHIVE" -gt 0 ] || [ "$MISSING_HASH" -gt 0 ]; then
  SEVERITY="HIGH"
elif [ "$NO_TRAILER" -gt 0 ] || [ "$MULTIPLE_TRAILERS" -gt 0 ]; then
  SEVERITY="MEDIUM"
else
  SEVERITY="LOW"
fi

printf '## Summary\n\n'
printf -- '- **Drift count:** %s\n' "$ITEM_COUNT"
printf -- '- **Severity:** %s\n' "$SEVERITY"
printf -- '- **Missing archive:** %s\n' "$MISSING_ARCHIVE"
printf -- '- **Missing hash:** %s\n' "$MISSING_HASH"
printf -- '- **Multiple trailers:** %s\n' "$MULTIPLE_TRAILERS"
printf -- '- **No trailer:** %s\n' "$NO_TRAILER"
printf -- '- **Warnings:** %s\n\n' "$WARN_COUNT"

# Notes section (warnings)
if [ "$WARN_COUNT" -gt 0 ]; then
  printf '## Notes\n\n'
  printf '%s' "$REPORT_JSON" \
    | sed -n 's/.*"warnings":\[\(.*\)\],"items".*/\1/p' \
    | tr ',' '\n' \
    | sed 's/^[[:space:]]*"\(.*\)"[[:space:]]*$/- \1/' \
    | grep -v '^-$'
  printf '\n'
fi

# Helper: print a category section. Uses awk to extract
# each item's fields and format them.
# Args: $1 = category key, $2 = section heading
print_category() {
  KEY="$1"
  HEADING="$2"
  COUNT=$(count_category "$KEY")
  if [ "$COUNT" = "0" ]; then return 0; fi
  printf '## %s\n\n' "$HEADING"
  # Extract items one at a time. The JSON for an item is
  # balanced braces; for our generated JSON (no nested
  # objects inside items), each item is a single line.
  # We use a line-by-line approach: split on "}," then trim.
  printf '%s' "$REPORT_JSON" \
    | awk -v k="$KEY" '
      {
        n = split($0, parts, "},")
        for (i = 1; i <= n; i++) {
          item = parts[i]
          # Trim leading { and trailing }
          sub(/^[[:space:]]*\{/, "", item)
          sub(/}[[:space:]]*$/, "", item)
          if (item ~ "\"category\":[[:space:]]*\"" k "\"") {
            h = ""; sh = ""; tid = ""; subj = ""; act = ""; note = ""
            if (match(item, /"hash":[[:space:]]*"[a-f0-9]+"/)) {
              h = substr(item, RSTART, RLENGTH)
              gsub(/"hash":[[:space:]]*"|"/, "", h)
            }
            if (match(item, /"shortHash":[[:space:]]*"[a-f0-9]+"/)) {
              sh = substr(item, RSTART, RLENGTH)
              gsub(/"shortHash":[[:space:]]*"|"/, "", sh)
            }
            if (match(item, /"taskId":[[:space:]]*"T-[0-9]+"/)) {
              tid = substr(item, RSTART, RLENGTH)
              gsub(/"taskId":[[:space:]]*"|"/, "", tid)
            }
            if (match(item, /"subject":[[:space:]]*"[^"]*"/)) {
              subj = substr(item, RSTART, RLENGTH)
              gsub(/"subject":[[:space:]]*"|"/, "", subj)
            }
            if (match(item, /"action":[[:space:]]*"[^"]*"/)) {
              act = substr(item, RSTART, RLENGTH)
              gsub(/"action":[[:space:]]*"|"/, "", act)
            }
            if (match(item, /"note":[[:space:]]*"[^"]*"/)) {
              note = substr(item, RSTART, RLENGTH)
              gsub(/"note":[[:space:]]*"|"/, "", note)
            }
            printf "- **%s**\n", (h != "" ? h : (sh != "" ? sh : "(no hash)"))
            if (tid != "") printf "  - **Task:** %s\n", tid
            if (subj != "") printf "  - **Subject:** %s\n", subj
            if (note != "") printf "  - **Note:** %s\n", note
            if (act != "") printf "  - **Action:** %s\n", act
            printf "\n"
          }
        }
      }
    '
}

print_category "missing-archive" "Missing archive"
print_category "missing-hash" "Missing hash"
print_category "multiple-trailers" "Multiple trailers"
print_category "no-trailer" "No trailer"

# Footer
printf -- '---\n\n'
printf 'Generated by drift-report.md.sh (no-LLM path). Source: DriftReport JSON from verifier-core.ts.\n'
